version: "2"

services:

  db:
    image: postgres
    volumes:
    - /var/lib/postgresql
    restart: always

  corenlp:
    image: lucasnoah/corenlp
    ports:
      - "8081:8081"
      - "9990:9990"


  web:
    build: .
    command: gunicorn -w 3 -b 0.0.0.0 litmetricscore.wsgi
    ports:
      - "8000:8000"
    links:
      - redis:redis
      - corenlp:corenlp
      - db
    depends_on:
      - migration
    volumes:
      - .:/code
      - /home/litmetricscore/media:/srv/code/media

    env_file:
      - ./secrets.env


  celery:
    build: .
    command: celery -A litmetricscore worker -l info
    links:
      - redis:redis
      - corenlp:corenlp
      - db
    volumes:
      - /home/litmetricscore/media:/srv/code/media
    env_file:
      - ./secrets.env

  migration:
    build: .
    command: bash -c 'dockerize -wait tcp://db:5432 && python mange.py makemigrations && python manage.py migrate'
    links:
      - db
    depends_on:
      - db
    env_file:
      - ./secrets.env

  redis:
    image: redis

 
