version: "2"

services:

  data:
    image: cogniteev/echo
    command: echo 'Data Container for PostgreSQL'
    volumes:
      - /var/lib/postgresql/data

  db:
    restart: allways
    image: postgres
    volumes_from:
    - data
    restart: always

  corenlp:
    image: lucasnoah/corenlp
    ports:
      - "8081:8081"
      - "9990:9990"


  web:
    build: .
    command:  bash -c "sleep 3 && python manage.py runserver 0.0.0.0:8000" #gunicorn -w 3 -b 0.0.0.0 litmetricscore.wsgi
    ports:
      - "8000:8000"
    links:
      - redis:redis
      - corenlp:corenlp
      - db
    depends_on:
      - migration
    working_dir: /code
    volumes:
      - .:/code
      - ./media:/media

    env_file:
      - ./secrets.env


  celery:
    build: .
    command: celery -A litmetricscore worker -l info
    links:
      - redis:redis
      - corenlp:corenlp
      - db
    volumes_from:
      - web
    env_file:
      - ./secrets.env

  migration:
    build: .
    command: bash -c 'dockerize -wait tcp://db:5432 && python manage.py makemigrations && python manage.py migrate'
    links:
      - db
    depends_on:
      - db
    env_file:
      - ./secrets.env

  redis:
    image: redis


