# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-07 21:40
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorpusItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('public', models.BooleanField(default=False)),
                ('is_processing', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CorpusItemCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('corpus_items', models.ManyToManyField(blank=True, to='core.CorpusItem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CorpusItemFilter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('filter_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('corpus_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.CorpusItem')),
            ],
        ),
        migrations.CreateModel(
            name='SentenceDependency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('dep', models.CharField(max_length=25)),
                ('dependent', models.IntegerField()),
                ('dependent_gloss', models.CharField(max_length=100)),
                ('governor', models.IntegerField()),
                ('governor_gloss', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TextFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=b'')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WordToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('after', models.CharField(max_length=100)),
                ('before', models.CharField(max_length=100)),
                ('character_offset_begin', models.IntegerField()),
                ('character_offset_end', models.IntegerField()),
                ('index', models.IntegerField()),
                ('lemma', models.CharField(max_length=100)),
                ('ner', models.CharField(max_length=25)),
                ('original_text', models.CharField(max_length=100)),
                ('pos', models.CharField(max_length=12)),
                ('speaker', models.CharField(blank=True, max_length=25)),
                ('word', models.CharField(max_length=100)),
                ('is_stopword', models.BooleanField(default=False)),
                ('wordnet_id', models.IntegerField(default=0)),
                ('sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Sentence')),
            ],
        ),
        migrations.AddField(
            model_name='corpusitem',
            name='text_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.TextFile'),
        ),
        migrations.AddField(
            model_name='corpusitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
