# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-14 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_lockedwordtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpusitemcollection',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
