# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-23 23:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_remove_textfile_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorpusItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('text_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.TextFile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('corpus_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.CorpusItem')),
            ],
        ),
        migrations.CreateModel(
            name='SentenceDependency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('dep', models.CharField(max_length=25)),
                ('dependent', models.IntegerField()),
                ('dependent_gloss', models.CharField(max_length=100)),
                ('governor', models.IntegerField()),
                ('governor_gloss', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WordToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('after', models.CharField(max_length=100)),
                ('before', models.CharField(max_length=100)),
                ('character_offset_begin', models.IntegerField()),
                ('character_offset_end', models.IntegerField()),
                ('index', models.IntegerField()),
                ('lemma', models.CharField(max_length=100)),
                ('ner', models.CharField(max_length=25)),
                ('original_text', models.CharField(max_length=100)),
                ('pos', models.CharField(max_length=12)),
                ('speaker', models.CharField(max_length=25)),
                ('word', models.CharField(max_length=100)),
            ],
        ),
    ]
