# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-25 03:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_corpusitem_sentence_sentencedependency_wordtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordtoken',
            name='is_stopword',
            field=models.BooleanField(default=False),
        ),
    ]
