# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_wordtoken_is_stopword'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpusitem',
            name='is_processing',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='corpusitem',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
