# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20160201_0328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wordtoken',
            name='speaker',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
