# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-01 20:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20160201_0559'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordtoken',
            name='sentence',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.Sentence'),
            preserve_default=False,
        ),
    ]
