# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20160204_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='corpusitemcollection',
            name='title',
            field=models.CharField(default='name', max_length=100),
            preserve_default=False,
        ),
    ]
