# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 00:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_corpusitemcollection_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corpusitem',
            name='corpus_item_collection',
        ),
        migrations.AddField(
            model_name='corpusitemcollection',
            name='corpus_items',
            field=models.ManyToManyField(to='core.CorpusItem'),
        ),
    ]
