# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20160205_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpusitemcollection',
            name='corpus_items',
            field=models.ManyToManyField(blank=True, to='core.CorpusItem'),
        ),
    ]
