# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-13 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20160212_2212'),
        ('topic_modeling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicmodelgroup',
            name='collections',
            field=models.ManyToManyField(to='core.CorpusItemCollection'),
        ),
    ]
