# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-14 05:07
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic_modeling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicmodelgroup',
            name='method',
            field=models.CharField(default=b'lda', max_length=30),
        ),
        migrations.AddField(
            model_name='topicmodelgroup',
            name='options',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
