# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-13 01:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic_modeling', '0002_topicmodelgroup_collections'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicmodelgroup',
            name='created',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime(2016, 2, 13, 1, 29, 44, 679492)),
            preserve_default=False,
        ),
    ]
