# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-30 04:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic_modeling', '0003_auto_20160618_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='u_mass',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='topicmodelgroup',
            name='options',
            field=models.TextField(),
        ),
    ]
